### ISSUE TITLE
Scrolling

### ISSUE THREAD

**Issue by nitromesyeti** [ijzm/Quack#1]
The screen only scrolls to a side when P1 (the pink duck) moves, while when P2 goes off the visible screen area, the screen won't scroll.

**Comment by ijzm** [comment]
I added that the screen will lock to the middle of both players (not yet in github)
Working on adding boundaries to the camera
will work on that later. gotta go

**Comment by ijzm** [comment]
https://github.com/ijzm/Quack/commit/85614497fe2541f433cd800a4a26581efffb272c
Fixed ;)
