### ISSUE TITLE
Shooting problems

### ISSUE THREAD

**Issue by nitromesyeti** [ijzm/Quack#2]
I found 3 problems while playtesting Quack so far concerning shooting:
1. The bullets now (again) are spawned from the center of the ducks' body and not from their mouth, which had apparently been fixed but now the glitch is back.
2. Player 2 won't shoot bullets at all.
3. Maybe you could implement some code for the player not to be able to pick up another bullet pack once one has already been collected, so that the other duck is still able to grab its pack as well.

**Comment by ijzm** [comment]
Fixed on https://github.com/ijzm/Quack/commit/21770d11046d1b31c1ab0aef8272f5238c993d6d
