### ISSUE TITLE
Press space to continue

### ISSUE THREAD

**Issue by nitromesyeti** [ijzm/Quack#3]
Maybe space can also be pressed to proceed to the following level, just to add ease to the player environment.

**Comment by ijzm** [comment]
Will add... gotta leave now.. will continue at night

**Comment by nitromesyeti** [comment]
Okay.

**Comment by ijzm** [comment]
https://github.com/ijzm/Quack/commit/b98ecca10ac3774e4ddd41046a07ab8c166522be
Done ;)
