### ISSUE TITLE
Not all gummies glitch

### ISSUE THREAD

**Issue by nitromesyeti** [ijzm/Quack#4]
Sometimes after level 3, levels can be completed without eating all of the gummies, though this is a minor bug.

**Comment by ijzm** [comment]
Found the issue: Stars are not being counted in the "how many you have to eat"-variable, but when you eat them, they reduce that variable. Will fix in a min

**Comment by ijzm** [comment]
Fixed https://github.com/ijzm/Quack/commit/7c98604708db36d75421c4a8d3b4e2620e5b4e7b
