### ISSUE TITLE
Health boxes problems

### ISSUE THREAD

**Issue by nitromesyeti** [ijzm/Quack#6]
Health boxes are supposed to scroll "along" with the player screen but they remain in one place, making them invisible if one of the ducks is on the other side.
Also, the health boxes are currently positioned inverted to the way the're supposed to. I thought I had told you pink to the right and blue to the left and if that wasn't the case I'm sorry - I was wrong.

**Comment by ijzm** [comment]
That was me forgetting to put one line of code... will fix when i finish working on this horrible horrible horrible code :P

**Comment by nitromesyeti** [comment]
Why are you so mean to your code :(

**Comment by ijzm** [comment]
Fixed https://github.com/ijzm/Quack/commit/4405d0bff7fec6c65d612ff008de0ae1631cfcfe
