### ISSUE TITLE
Main game music

### ISSUE THREAD

**Issue by nitromesyeti** [ijzm/Quack#7]
Is not playing.

**Comment by ijzm** [comment]
it is playing for me

**Comment by nitromesyeti** [comment]
I mean the in-game music, not the menu. It's really not playing for me for some reason :/

**Comment by ijzm** [comment]
Thats weird.. mits palyiong for me... Which browser?

**Comment by nitromesyeti** [comment]
Safari

**Comment by ijzm** [comment]
Cant believe im doing this.. but downloading safari for windows...

**Comment by ijzm** [comment]
game wont even launch on safari :s

**Comment by nitromesyeti** [comment]
Lol, well it actually launches and the menu music gets to play. It's just the in-game track that I cannot hear

**Comment by ijzm** [comment]
Do you know how to get the console working on safari for mac?

**Comment by nitromesyeti** [comment]
Actually I don't know, but chances are if you're trying to run Safari on Windows it might just not work

**Comment by ijzm** [comment]
Go to preferences -> advanced -> show developer menu on menu bar
then go to develop -> show error console

**Comment by ijzm** [comment]
Then with that open, restart the page, and watch the console
copy paste what you see when music is supposed to play

**Comment by nitromesyeti** [comment]
Okay
Hold on a second, I think the option to  show developer thing is not on the list

**Comment by nitromesyeti** [comment]
Done
Now wait until I get what you're asking

**Comment by ijzm** [comment]
Get on NW so we can explain better?

**Comment by nitromesyeti** [comment]
[Log] Phaser v2.4.4 | Pixi.js v2.2.9 | WebGL | WebAudio | http://phaser.io (phaser.js, line 34450)
[Log] PLAY 2p (MainMenu.js, line 47)

**Comment by nitromesyeti** [comment]
Nothing else shows up

**Comment by nitromesyeti** [comment]
Okay

**Comment by ijzm** [comment]
Try again now? I changed the file... maybe that was the problem?

**Comment by nitromesyeti** [comment]
<img width="1280" alt="captura de pantalla 2016-01-27 a las 2 33 03 p m" src="https://cloud.githubusercontent.com/assets/16844475/12622193/f449df6a-c502-11e5-8f93-995e242550e5.png">
Here's a screencap of what the thing looks like

**Comment by nitromesyeti** [comment]
Works now, oh well.
