### ISSUE TITLE
Shooting problems part 2

### ISSUE THREAD

**Issue by nitromesyeti** [ijzm/Quack#8]
*If played in the 1-player version, the game will freeze and not run at all upon trying to shoot a bullet.
*If one player collects a bullet powerup, both of them get the ability to shoot instead of only the duck who grabbed it.
*Like in Cave Chaos 2, if one bullet pack has been collected by one of the ducks, the other bullet pack should not be available to pick up by the same duck. This is to give the chance to both players to have a pack for their own. Although this is just enhancement, not a bug. I mentioned this on the previous shooting problems post now closed.

**Comment by ijzm** [comment]
Fixed part 1 https://github.com/ijzm/Quack/commit/4405d0bff7fec6c65d612ff008de0ae1631cfcfe

**Comment by ijzm** [comment]
Fixed https://github.com/ijzm/Quack/commit/de65de8af9e5bfb18e7ee9d96158ba8f0fa5a630
